### ISSUE TITLE
I have a problem with some special characters

### ISSUE THREAD

**Issue by ghost** [Srchronotrigger/Message-2Harkinian#2]
Hi mate!

I'm using your tool to translate dialog texts into Spanish and it works great but I'm having problems with some special characters like:

"¡", "¿", "á", "é", "í", "ó", "ú", "ñ"

When entering them into texts they give wrong equivalents like:

"¡" -> "Âí"
"á" -> "ÄÍ"

I haven't checked it but it's very likely that their uppercase equivalents also produce the same effect
"Á", "É", "Í", "Ó", "Ú", "Ñ"

If you could solve or guide me on how to associate these special characters correctly I would really appreciate it! Greetings!!

![Sin_titulo](https://github.com/user-attachments/assets/a29767c9-3422-430b-9735-a90c28debdb5)

**Comment by Srchronotrigger** [comment]
Hi lordgifrun! How are you?

Let's to check what is occurring in low level:

When you write a text using only ascii characters we have one byte for each letter
So "Hello" in hexadecimal must to be `0x48` `0x65` `0x6C` `0x6C` `0x6F` if you use linux you can type
```
man ascii
```
on the terminal to see the full ascii character list.

But, if you write "¿cómo estás?" for example? Let's try:
`0xC2` `0xBf` `0x63` `0xC3` `0xB3` `0x6D` `0x6F` `0x20` `0x65` `0x73` `0x74` `0xC3` `0xA1` `0x73` `0x3F` if you count the bytes of this output, you will see that have more bytes than letters, and indeed, see the string of these bytes it will be `Â¿cÃ³mo estÃ¡s`.

This happens because characters with accents are represented with two bytes and the game processes only one byte for each digit, so when we use Ã for example, the interpreter sees that this letter is represented by two bytes `0xC3` and `0x83` and write them on the file, but since the game reads one byte for each digit it ends up understanding that `0xC3` and `0x83` are different letters.

This problem also occurs in my language, which is Portuguese, and I believe with most Latin languages.

Fortunately, the Message 2Harkinian has two methods to solve this.

You can choose some letters that are not used in Spanish, like `Ää` `Öö` I suppose, and use them instead of the letters you want to use. You can do this by modifying the HashMap `initializeaspecialCharsHashMap()` that is in the `Constants.java` file. This HashMap is responsible for replacing certain characters with the correct values ​​in hex. If you look closely, I already do this with some cases like:
```
specialChars.put("ä", "9A"); // LOWERCASE_A_TREMA_UMLAUT
specialChars.put("ã", "9A"); // LOWERCASE_A_TILDE (PROVISÓRIO)
...
specialChars.put("Ä", "83"); // UPPERCASE_A_TREMA_UMLAUT
specialChars.put("Ã", "83"); // UPPERCASE_A_TILDE
```

With this, if you type `Ä` or `Ã`, the value `0x83` will be placed in the game file, which will make it display `Ä` on the screen.

If you don't want to modify the program, you can use the hexadecimal value directly in your translation dialog file with the slash command `\xNN`, where `NN` is a hexadecimal value. In this example, `\x` would be `\x83` to show the character Ä in the game dialog.

After that, along with your mod, you can add a texture that replaces these letters with the ones you want, this will make the correct letters appear in the game. In the print below, I am using the method described:

![Screenshot of zelda majora's mask showing text in portuguese with accents](https://i.postimg.cc/SKZKc9jV/Screenshot-2.png)

In the future I intend to place this function directly in the configs button found in the program interface so that it will be easier to make these substitutions, but at the moment I am busy and because of that I would like to apologize for taking so long to respond to you. In any case, I hope my answer has clarified your doubt, good luck with your project and may God bless you immensely. 🙂

**Comment by ghost** [comment]
Thanks for your answer!!!

With this in mind I think I can continue with "the translation odyssey" :D

It also clarifies my doubts about how to do the same in other Latin languages ​​(some people asked me if it was possible and I wasn't sure how to respond yet)

Thanks again for your answer and especially for the tool to process the text!! Greetings buddy!! :D
